// Package shims owns HarnessRelay's user-local command shim configuration and files.
package shims

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const (
	ConfigVersion   = 1
	OwnershipMarker = "# Generated by HarnessRelay. Do not edit manually."
	DefaultBackend  = BackendPTY
)

type Backend string

const (
	BackendPTY    Backend = "pty"
	BackendTMUX   Backend = "tmux"
	BackendDirect Backend = "direct"
)

type Config struct {
	Version                   int              `json:"version"`
	ShimDir                   string           `json:"shim_dir"`
	DefaultBackend            Backend          `json:"default_backend"`
	DaemonUnavailableFallback Backend          `json:"daemon_unavailable_fallback"`
	Entries                   map[string]Entry `json:"entries"`
}

type Entry struct {
	Enabled    bool    `json:"enabled"`
	ShimPath   string  `json:"shim_path"`
	RealBinary string  `json:"real_binary"`
	Harness    string  `json:"harness"`
	Backend    Backend `json:"backend"`
	CreatedBy  string  `json:"created_by"`
}

type Target struct {
	Name        string
	DisplayName string
	Command     string
	Description string
}

type InstallOptions struct {
	Name       string
	RealBinary string
	Backend    Backend
	Harnessctl string
	Force      bool
	Path       string
	ConfigPath string
	ShimDir    string
}

type PathState struct {
	Present         bool
	Index           int
	RealBinaryDir   string
	RealBinaryIndex int
	Active          bool
}

func KnownTargets() []Target {
	return []Target{
		{Name: "codex", DisplayName: "Codex", Command: "codex", Description: "OpenAI Codex CLI"},
		{Name: "opencode", DisplayName: "OpenCode", Command: "opencode", Description: "OpenCode terminal UI"},
		{Name: "grok", DisplayName: "Grok", Command: "grok", Description: "xAI Grok CLI"},
	}
}

func DefaultConfigPath() (string, error) {
	if override := os.Getenv("HARNESSRELAY_SHIMS_CONFIG"); override != "" {
		return filepath.Abs(override)
	}
	base, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("shims: determine config directory: %w", err)
	}
	return filepath.Join(base, "harnessrelay", "shims.json"), nil
}

func DefaultShimDir() (string, error) {
	if override := os.Getenv("HARNESSRELAY_SHIMS_DIR"); override != "" {
		return filepath.Abs(override)
	}
	if base := os.Getenv("XDG_DATA_HOME"); base != "" {
		return filepath.Join(base, "harnessrelay", "shims"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("shims: determine home directory: %w", err)
	}
	return filepath.Join(home, ".local", "share", "harnessrelay", "shims"), nil
}

func NewConfig(shimDir string) Config {
	return Config{
		Version:                   ConfigVersion,
		ShimDir:                   shimDir,
		DefaultBackend:            DefaultBackend,
		DaemonUnavailableFallback: BackendDirect,
		Entries:                   make(map[string]Entry),
	}
}

func Load(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		shimDir, dirErr := DefaultShimDir()
		if dirErr != nil {
			return Config{}, dirErr
		}
		return NewConfig(shimDir), nil
	}
	if err != nil {
		return Config{}, fmt.Errorf("shims: read config: %w", err)
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("shims: malformed config: %w", err)
	}
	if err := ValidateConfig(&cfg); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

func ValidateConfig(cfg *Config) error {
	if cfg.Version != ConfigVersion {
		return fmt.Errorf("shims: unsupported config version %d", cfg.Version)
	}
	if cfg.ShimDir == "" {
		return errors.New("shims: config shim_dir is required")
	}
	if !ValidBackend(cfg.DefaultBackend) {
		return fmt.Errorf("shims: invalid default backend %q", cfg.DefaultBackend)
	}
	if !ValidBackend(cfg.DaemonUnavailableFallback) {
		return fmt.Errorf("shims: invalid daemon fallback %q", cfg.DaemonUnavailableFallback)
	}
	if cfg.Entries == nil {
		cfg.Entries = make(map[string]Entry)
	}
	for name, entry := range cfg.Entries {
		if err := ValidateName(name); err != nil {
			return err
		}
		if entry.RealBinary == "" || !filepath.IsAbs(entry.RealBinary) {
			return fmt.Errorf("shims: entry %q real_binary must be absolute", name)
		}
		if !ValidBackend(entry.Backend) {
			return fmt.Errorf("shims: entry %q has invalid backend %q", name, entry.Backend)
		}
	}
	return nil
}

func Save(path string, cfg Config) error {
	if err := ValidateConfig(&cfg); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("shims: create config directory: %w", err)
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("shims: encode config: %w", err)
	}
	data = append(data, '\n')
	tmp, err := os.CreateTemp(filepath.Dir(path), ".shims-*.json")
	if err != nil {
		return fmt.Errorf("shims: create temporary config: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("shims: replace config: %w", err)
	}
	return nil
}

func Install(opts InstallOptions) (Entry, error) {
	if err := ValidateName(opts.Name); err != nil {
		return Entry{}, err
	}
	if !ValidBackend(opts.Backend) {
		return Entry{}, fmt.Errorf("shims: invalid backend %q", opts.Backend)
	}
	configPath := opts.ConfigPath
	if configPath == "" {
		var err error
		configPath, err = DefaultConfigPath()
		if err != nil {
			return Entry{}, err
		}
	}
	cfg, err := Load(configPath)
	if err != nil {
		return Entry{}, err
	}
	shimDir := opts.ShimDir
	if shimDir == "" {
		shimDir = cfg.ShimDir
	}
	shimDir, err = filepath.Abs(shimDir)
	if err != nil {
		return Entry{}, err
	}
	cfg.ShimDir = shimDir
	pathValue := opts.Path
	if pathValue == "" {
		pathValue = os.Getenv("PATH")
	}
	realBinary := opts.RealBinary
	if realBinary == "" {
		realBinary, err = ResolveRealBinary(opts.Name, pathValue, shimDir)
		if err != nil {
			return Entry{}, err
		}
	} else {
		realBinary, err = validateRealBinary(realBinary, filepath.Join(shimDir, opts.Name))
		if err != nil {
			return Entry{}, err
		}
	}
	harnessctl := opts.Harnessctl
	if harnessctl == "" {
		harnessctl, err = os.Executable()
		if err != nil {
			return Entry{}, fmt.Errorf("shims: resolve harnessctl: %w", err)
		}
	}
	harnessctl, err = filepath.Abs(harnessctl)
	if err != nil {
		return Entry{}, err
	}
	if err := os.MkdirAll(shimDir, 0o755); err != nil {
		return Entry{}, fmt.Errorf("shims: create shim directory: %w", err)
	}
	shimPath := filepath.Join(shimDir, opts.Name)
	if err := writeShim(shimPath, opts.Name, harnessctl, opts.Force); err != nil {
		return Entry{}, err
	}
	if err := VerifyShimFile(shimPath); err != nil {
		return Entry{}, err
	}
	entry := Entry{
		Enabled:    true,
		ShimPath:   shimPath,
		RealBinary: realBinary,
		Harness:    opts.Name,
		Backend:    opts.Backend,
		CreatedBy:  "harnessrelay",
	}
	cfg.Entries[opts.Name] = entry
	if err := Save(configPath, cfg); err != nil {
		return Entry{}, err
	}
	return entry, nil
}

func Reshim(configPath, harnessctl string) error {
	cfg, err := Load(configPath)
	if err != nil {
		return err
	}
	if harnessctl == "" {
		harnessctl, err = os.Executable()
		if err != nil {
			return err
		}
	}
	harnessctl, err = filepath.Abs(harnessctl)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(cfg.ShimDir, 0o755); err != nil {
		return err
	}
	for _, name := range SortedEntryNames(cfg) {
		entry := cfg.Entries[name]
		if !entry.Enabled {
			continue
		}
		if err := writeShim(entry.ShimPath, name, harnessctl, false); err != nil {
			return err
		}
	}
	return nil
}

func Uninstall(configPath string, names []string) error {
	cfg, err := Load(configPath)
	if err != nil {
		return err
	}
	for _, name := range names {
		entry, ok := cfg.Entries[name]
		if !ok {
			return fmt.Errorf("shims: %q is not installed", name)
		}
		owned, err := IsManagedShim(entry.ShimPath)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if err == nil && !owned {
			return fmt.Errorf("shims: refusing to remove unmanaged file %s", entry.ShimPath)
		}
		if err == nil {
			if err := os.Remove(entry.ShimPath); err != nil {
				return fmt.Errorf("shims: remove %s: %w", entry.ShimPath, err)
			}
		}
		delete(cfg.Entries, name)
	}
	return Save(configPath, cfg)
}

func UninstallAll(configPath string) error {
	cfg, err := Load(configPath)
	if err != nil {
		return err
	}
	return Uninstall(configPath, SortedEntryNames(cfg))
}

func ResolveRealBinary(name, pathValue, shimDir string) (string, error) {
	candidates, err := ResolveRealBinaryCandidates(name, pathValue, shimDir)
	if err != nil {
		return "", err
	}
	return candidates[0], nil
}

func ResolveRealBinaryCandidates(name, pathValue, shimDir string) ([]string, error) {
	if err := ValidateName(name); err != nil {
		return nil, err
	}
	canonicalShimDir := canonicalPath(shimDir)
	var candidates []string
	seen := make(map[string]struct{})
	for _, dir := range filepath.SplitList(pathValue) {
		if dir == "" || canonicalPath(dir) == canonicalShimDir {
			continue
		}
		candidate := filepath.Join(dir, name)
		info, err := os.Stat(candidate)
		if err != nil || info.IsDir() || info.Mode()&0o111 == 0 {
			continue
		}
		owned, err := IsManagedShim(candidate)
		if err == nil && owned {
			continue
		}
		validated, err := validateRealBinary(candidate, filepath.Join(shimDir, name))
		if err == nil {
			if _, ok := seen[validated]; ok {
				continue
			}
			seen[validated] = struct{}{}
			candidates = append(candidates, validated)
		}
	}
	if len(candidates) == 0 {
		return nil, fmt.Errorf("shims: real binary %q not found on PATH outside %s", name, shimDir)
	}
	return candidates, nil
}

func ValidateRuntimeEntry(name string, entry Entry) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	real, err := validateRealBinary(entry.RealBinary, entry.ShimPath)
	if err != nil {
		return err
	}
	if owned, err := IsManagedShim(real); err == nil && owned {
		return fmt.Errorf("shims: recursion prevented: real binary is a HarnessRelay shim: %s", real)
	}
	return nil
}

func IsManagedShim(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	return strings.Contains(string(data), OwnershipMarker), nil
}

func VerifyShimFile(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("shims: verify generated shim: %w", err)
	}
	if info.IsDir() || info.Mode()&0o111 == 0 {
		return fmt.Errorf("shims: generated shim is not executable: %s", path)
	}
	owned, err := IsManagedShim(path)
	if err != nil {
		return fmt.Errorf("shims: verify generated shim: %w", err)
	}
	if !owned {
		return fmt.Errorf("shims: generated shim ownership marker is missing: %s", path)
	}
	return nil
}

func GeneratedShim(name, harnessctl string) string {
	return "#!/bin/sh\n" + OwnershipMarker + "\nexec " + shellQuote(harnessctl) +
		" shim exec " + shellQuote(name) + " -- \"$@\"\n"
}

func AnalyzePath(shimDir, realBinary, pathValue string) PathState {
	state := PathState{Index: -1, RealBinaryIndex: -1, RealBinaryDir: filepath.Dir(realBinary)}
	canonicalShim := canonicalPath(shimDir)
	canonicalRealDir := canonicalPath(filepath.Dir(realBinary))
	for index, dir := range filepath.SplitList(pathValue) {
		if state.Index == -1 && canonicalPath(dir) == canonicalShim {
			state.Present = true
			state.Index = index
		}
		if state.RealBinaryIndex == -1 && canonicalPath(dir) == canonicalRealDir {
			state.RealBinaryIndex = index
		}
	}
	state.Active = state.Present && (state.RealBinaryIndex == -1 || state.Index < state.RealBinaryIndex)
	return state
}

func SortedEntryNames(cfg Config) []string {
	names := make([]string, 0, len(cfg.Entries))
	for name := range cfg.Entries {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func ValidBackend(backend Backend) bool {
	return backend == BackendPTY || backend == BackendTMUX || backend == BackendDirect
}

func ParseBackend(value string) (Backend, error) {
	backend := Backend(value)
	if !ValidBackend(backend) {
		return "", fmt.Errorf("shims: backend must be pty, tmux, or direct")
	}
	return backend, nil
}

func ValidateName(name string) error {
	if name == "" || name == "." || name == ".." || filepath.Base(name) != name ||
		strings.ContainsAny(name, `/\`) {
		return fmt.Errorf("shims: invalid shim name %q", name)
	}
	for _, r := range name {
		if !(r == '-' || r == '_' || r == '.' || r >= '0' && r <= '9' ||
			r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z') {
			return fmt.Errorf("shims: invalid shim name %q", name)
		}
	}
	return nil
}

func writeShim(path, name, harnessctl string, force bool) error {
	if info, err := os.Stat(path); err == nil {
		if info.IsDir() {
			return fmt.Errorf("shims: destination is a directory: %s", path)
		}
		owned, readErr := IsManagedShim(path)
		if readErr != nil {
			return readErr
		}
		if !owned && !force {
			return fmt.Errorf("shims: refusing to overwrite unmanaged file %s (use --force)", path)
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".shim-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o755); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.WriteString(GeneratedShim(name, harnessctl)); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func validateRealBinary(path, shimPath string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return "", fmt.Errorf("shims: real binary %s: %w", absolute, err)
	}
	if info.IsDir() || info.Mode()&0o111 == 0 {
		return "", fmt.Errorf("shims: real binary is not executable: %s", absolute)
	}
	if canonicalPath(absolute) == canonicalPath(shimPath) {
		return "", fmt.Errorf("shims: recursion prevented: real binary resolves to shim %s", shimPath)
	}
	if resolved, err := filepath.EvalSymlinks(absolute); err == nil {
		absolute = resolved
	}
	return absolute, nil
}

func canonicalPath(path string) string {
	absolute, err := filepath.Abs(path)
	if err != nil {
		absolute = path
	}
	if resolved, err := filepath.EvalSymlinks(absolute); err == nil {
		return resolved
	}
	if runtime.GOOS == "windows" {
		return strings.ToLower(absolute)
	}
	return absolute
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
