// Package dashboard embeds the production web dashboard into harnessd.
package dashboard

import (
	"embed"
	"io/fs"
)

// dist is generated by npm run build before release binaries are compiled.
//
//go:embed all:dist
var dist embed.FS

func FS() fs.FS {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		panic(err)
	}
	return sub
}
